application: gajukbhat
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "15m"

handlers:
# index files
- url: /(.*)/
  static_files: public/\1/index.html
  upload: public/(.*)/index.html

# site root
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /archives
  static_files: public/archives/index.html
  upload: public/archives/index.html

- url: /about
  static_files: public/about/index.html
  upload: public/about/index.html

- url: /resume
  static_files: public/resume/index.html
  upload: public/resume/index.html

- url: /categories
  static_files: public/categories/index.html
  upload: public/categories/index.html

# categories have no '/', so can not cover by index files rule
- url: /categories/(.*)
  static_files: public/categories/\1/index.html
  upload: public/categories/(.*)/index.html

- url: /
  static_dir: public
